database:
  name: pricing-engine
  database_host: ${DATABASE_HOST}
  database_port: ${DATABASE_PORT}
  database_username: ${DATABASE_USERNAME}
  database_password: ${DATABASE_PASSWORD}

services:
  - name: pricing-engine
    runtime: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    envVars:
      - key: APP_ENV
        value: production
      - key: API_AUTH_TOKEN
        generateValue: true
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: "postgresql://postgres:7fwmwxvMFuOgM0fi@db.ylyflewubyvervbecfna.supabase.co:5432/postgres"
      - key: DATABASE_TYPE
        value: "postgresql"
